Mobile skeleton
Jhaman1895/Personal-Portfolio pull request #3
Opened 2022-06-04 15:20 UTC by Jhaman1895

Added works and about me sections to the mobile version skeleton using CSS Flexbox and Grid for the layouts.

2022-06-04 15:52 UTC, topeogunleye requested changes
> # Changes Required 
> ### Hi @Jhaman1895,
> Nice job, you are almost there.
> 
> ![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
> 
> ## (Highlights) Good Points: 
> * Good commit messages. :heavy_check_mark:
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
> * PR has a good summary :heavy_check_mark:
>
> ## (Changes Required) Aspects to improve: 
>- [ ]  Please check my inline comments.
> 
> ## [Optional] suggestions:
>- [ ]  Please check my inline comments.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> **Cheers and Happy coding! :clap::clap::clap:**
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear
> Please, remember to tag @topeogunleye in your question so I can receive the notification.
>
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-06-04 15:52 UTC, topeogunleye commented on index.html
> +            <h1>Tonic</h1>
- [ ] [OPTIONAL] There should be only one `h1` in an HTML file because of semantics. I kindly suggest that you make only your main title of "I’m Ayush! Glad to see you!" an `h1` and kindly make use of headers from `h2` down to `h6` for any other headers in your HTML file.
- [ ] [OPTIONAL] please kindly make changes and replace all other `h1` except your main title

2022-06-04 15:52 UTC, topeogunleye commented on index.html
> +            <h1>Multi-Post<br>
- [ ] [OPTIONAL] kindly make use of headers from `h2` down to `h6` for any other headers apart from your main title of "I’m Ayush! Glad to see you!" in your HTML file.

2022-06-04 15:52 UTC, topeogunleye commented on index.html
> +            <h1>Tonic</h1>
- [ ] [OPTIONAL] kindly make use of headers from `h2` down to `h6` for any other headers apart from your main title of "I’m Ayush! Glad to see you!" in your HTML file.

2022-06-04 15:52 UTC, topeogunleye commented on index.html
> +            <h1>Multi-Post<br> Stories</h1>
- [ ] [OPTIONAL] kindly make use of headers from `h2` down to `h6` for any other headers apart from your main title of "I’m Ayush! Glad to see you!" in your HTML file.

2022-06-04 15:52 UTC, topeogunleye commented on index.html
> +        <h1 class="aboutMe header">About<br>Myself</h1>
- [ ] [OPTIONAL] kindly make use of headers from `h2` down to `h6` for any other headers apart from your main title of "I’m Ayush! Glad to see you!" in your HTML file.

2022-06-04 15:52 UTC, topeogunleye commented on index.html
> +        <div class="social-links">
- [ ] I kindly suggest that you change this div tag to a `<ul>` tag and make sure for each childeren `<a>` tag, there is an `li` tag. It will makes your HTML structure better

2022-06-04 15:52 UTC, topeogunleye commented on index.html
> +        <div class="social-links">
- [ ] I kindly suggest that you change this div tag to a `<ul>` tag and make sure for each childeren `<a>` tag, there is a `li` tag. It will makes your HTML structure better

2022-06-04 16:19 UTC, Jhaman1895 commented on index.html
> +        <h1 class="aboutMe header">About<br>Myself</h1>
Thanks so much for this helpful insight! I will be sure to fix this in the future. As it is Saturday and I am repeating week 1, I submitted the required changes and will definitely take care of the optional changes in the following week.

2022-06-04 16:19 UTC, Jhaman1895 commented on index.html
> +            <h1>Multi-Post<br> Stories</h1>
Thanks so much for this helpful insight! I will be sure to fix this in the future. As it is Saturday and I am repeating week 1, I submitted the required changes and will definitely take care of the optional changes in the following week.

2022-06-04 16:19 UTC, Jhaman1895 commented on index.html
> +            <h1>Tonic</h1>
Thanks so much for this helpful insight! I will be sure to fix this in the future. As it is Saturday and I am repeating week 1, I submitted the required changes and will definitely take care of the optional changes in the following week.

2022-06-04 16:19 UTC, Jhaman1895 commented on index.html
> +            <h1>Multi-Post<br>
Thanks so much for this helpful insight! I will be sure to fix this in the future. As it is Saturday and I am repeating week 1, I submitted the required changes and will definitely take care of the optional changes in the following week.

2022-06-04 16:19 UTC, Jhaman1895 commented on index.html
> +            <h1>Tonic</h1>
Thanks so much for this helpful insight! I will be sure to fix this in the future. As it is Saturday and I am repeating week 1, I submitted the required changes and will definitely take care of the optional changes in the following week.

2022-06-04 16:20 UTC, Jhaman1895 commented on index.html
> +        <div class="social-links">
Thanks for this valuable suggestion. I will take care of this immediately. Thank you!

2022-06-04 16:20 UTC, Jhaman1895 commented on index.html
> +        <div class="social-links">
Thanks for this valuable suggestion. I will take care of this immediately. Thank you!

2022-06-04 16:36 UTC, Kakalanp approved these changes
# STATUS: APPROVED :green_circle: 

### Your project is approved @Jhaman1895! :tada: 

There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :clinking_glasses: 

<img src="https://media.giphy.com/media/slOhiKAVFgwr6/giphy-downsized.gif" alt="almost there">

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-04 16:47 UTC, merged

2022-06-05 17:32 UTC, topeogunleye commented on index.html
> +        <h1 class="aboutMe header">About<br>Myself</h1>
I understand :+1:, Enjoy your weekend.